name: Get Google Drive Data

on: [push]

jobs:
  name: Get Google Drive Data
  runs-on: macOS-latest
  env:
    GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
    - name: Install CRAN packages
      run: Rscript -e 'install.packages(c("remotes", "googledrive", "dplyr", "stringr", "purrr", "here"))'
    - name: Run GoogleDrive script
      run: |
        source('scripts/Get-GoogleDrive-Data.R')
      shell: Rscript {0}